# SPDX-FileCopyrightText: 2021 Andrea Pappacoda <andrea@pappacoda.it>
#
# SPDX-License-Identifier: Apache-2.0

name: autopkgtest

on:
  push:
    paths-ignore: pistache.io/**
  pull_request:
    paths-ignore: pistache.io/**

# The default Debian shell (dash) is faster than bash at running scripts, and
# using bash when it is not needed doesn't make sense.
defaults:
  run:
    shell: sh

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        arch: [ amd64, arm64, armhf, i386, ppc64el ] # , s390x

    steps:
    - uses: actions/checkout@v2

    # The Debian repository is needed by autopkgtest-build-qemu when building
    # for foreign architectures, since the tool tries to install
    # linux-image-${{ matrix.arch }}, that is unavailable on Ubuntu; adding
    # the Debian Testing repo and lowering its priority solves the issue
    # while not risking to break the system mixing Debian and Ubuntu pkgs.
    # The pgp key required to use the repository is downloaded through the
    # debain-archive-keyring package, and instead of using the deprecated
    # apt-key utility to add the keyring to the trusted ones I use the
    # Signed-By option (deb822 source format), as recommended in the Debian
    # wiki (https://wiki.debian.org/DebianRepository/UseThirdParty).
    - name: Install dependencies
      run: |
        sudo apt -qq install debian-archive-keyring
        printf 'Enabled: yes\nTypes: deb\nURIs: http://debian-archive.trafficmanager.net/debian/\nSuites: testing\nComponents: main\nSigned-By: /usr/share/keyrings/debian-archive-keyring.gpg\n' | sudo tee /etc/apt/sources.list.d/debian.sources
        printf 'Package: *\nPin: release o=Debian,a=testing\nPin-Priority: 400\n' | sudo tee /etc/apt/preferences.d/99debian-testing
        sudo apt -qq update
        sudo apt-mark hold qemu-system-gui
        sudo apt -qq install genisoimage qemu-system/testing vmdb2/testing devscripts qemu-user-static/testing && sudo apt-mark auto qemu-user-static
        sudo apt -qq build-dep .

    # Build and install autopkgtest from the latest master (5.17), since
    # previous versions can't build non-x86 images. It is done in a nested /tmp
    # directory because otherwise debuild would try to write in /, resulting in
    # an error.
    - name: Install autopkgtest from source
      run: |
        mkdir --parent /tmp/autopkgtest-build
        curl --silent --output /tmp/autopkgtest-build/autopkgtest-master.tar --proto https --proto-default https --tlsv1.3 --http2-prior-knowledge https://salsa.debian.org/ci-team/autopkgtest/-/archive/master/autopkgtest-master.tar
        tar --extract --file=/tmp/autopkgtest-build/autopkgtest-master.tar --directory=/tmp/autopkgtest-build
        cd /tmp/autopkgtest-build/autopkgtest-master
        sudo apt -qq build-dep . --default-release=testing
        DEB_BUILD_OPTIONS=nocheck debuild --unsigned-source --unsigned-changes
        sudo apt -qq install ../autopkgtest*.deb
        cd -
        rm -rf /tmp/autopkgtest-build

    - name: Build image
      run: sudo autopkgtest-build-qemu --size 12G --architecture ${{ matrix.arch }} testing $HOME/autopkgtest-testing.img

    - name: Build Debian package source
      run: |
        ./debian/rules get-orig-source
        dpkg-source --build .

    # The increased timeout is needed because the CI can be too slow to boot
    # the image.
    - name: Run autopkgtest
      run: for retry in 1 2 3 4 5; do ((autopkgtest ../pistache_*.dsc -- qemu --dpkg-architecture=${{ matrix.arch }} --timeout-reboot=120 --ram-size=4096 --cpus=$(nproc) $HOME/autopkgtest-testing.img && break) || if [ retry != 5 ]; do sleep $((retry*retry)); else false; fi); done
