# SPDX-FileCopyrightText: 2021 Andrea Pappacoda <andrea@pappacoda.it>
#
# SPDX-License-Identifier: Apache-2.0

name: autopkgtest

on:
  push:
    paths-ignore: pistache.io/**
  pull_request:
    paths-ignore: pistache.io/**

# This ensures that jobs get canceled when force-pushing
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# The default Debian shell (dash) is faster than bash at running scripts, and
# using bash when it is not needed doesn't make sense.
defaults:
  run:
    shell: sh

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: debian:testing
      options: --privileged

    strategy:
      fail-fast: false
      matrix:
        arch: [ amd64, arm64, armhf, i386, ppc64el ] # , s390x

    steps:
    # The --no-install-recommends apt option is important, as installing
    # recommended packages causes autopkgtest to fail for arm64 and armhf;
    # I don't know why, I don't know how, I only know that it tooks hours to
    # figure it out.
    - name: Install dependencies
      run: |
        apt -y update
        apt -y install autopkgtest genisoimage qemu-system vmdb2 devscripts git

    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout Debian data
      uses: actions/checkout@v2
      with:
        ref: debian
        path: debian

    - name: Install build-deps
      run: apt -y build-dep . --no-install-recommends

    - name: Build image
      run: |
        debootstrap --arch ${{ matrix.arch }} testing $(mktemp --directory)
        autopkgtest-build-qemu --architecture ${{ matrix.arch }} --size 12G testing $HOME/autopkgtest-testing.img || exit_status=$?
        cat /tmp/tmp*/debootstrap/debootstrap.log
        exit $exit_status

    - name: Build Debian package source
      run: |
        uscan
        cd ../pistache-*/
        dpkg-source --build .

    # The increased timeout is needed because the CI can be too slow to boot
    # the image. --dpkg-architecture is needed because autopkgtest-virt-qemu
    # defaults to the host arch instead of reading it from the image.
    # The ram size is set to 3072 MB because the default 1 GiB is not enough
    # to build Pistache, the amount must be less than 4 GiB otherwise the i386
    # image won't boot, ppc64el requires it to be aligned to 256 MiB and an
    # amout not convertible to a GiB integer causes arm64 to fail, while extra
    # CPU cores can't be used as they can cause arm runs to fail with the error
    # below. Instead of explicitly calling autopkgtest-virt-qemu it should be
    # enough to just write qemu.
    # Currently this sometimes fails on i386 with
    #   <VirtSubproc>: failure: timed out waiting for 'login prompt on serial
    #     console'
    # on arm64 and armhf with
    #   host login: <VirtSubproc>: failure: The VM does not start a root shell
    #     on ttyS1 or hvc1 already. The only other supported login mechanism is
    #     through --user and -*** the guest ttyS0
    # on almost all architectures with
    #   ERROR: testbed failure: sent `auxverb_debug_fail', got `timeout',
    #     expected `ok...'

    - name: Run autopkgtest
      run: |
        exit_code=0
        autopkgtest ../pistache_*.dsc -- qemu --dpkg-architecture=${{ matrix.arch }} --timeout-reboot=120 --ram-size=3072 $HOME/autopkgtest-testing.img || exit_code=$?
        if [ $exit_code -eq 16 ]
        then
          echo "::warning::autopkgtest failed, but it's not your fault"
        else
          exit $exit_code
        fi
